### ISSUE TITLE
sharing xib files

### ISSUE THREAD

**Issue by abuazizeh** [SnowdogApps/SDForms#1]
when adding a custom cell (new xib file) and then try to use the cell in the SDform , I get  NSInternalInconsistencyException , because sdform tries to register the tablecell with sdform bundle.

my workaround:

downloaded the project itself and connected it as a library project instead of using cocoapods, then added my xib file to SdformResources.bunlde

**Comment by rkwiat89** [comment]
Thanks for feedback,

When you create your own fields, please override registerCellsInTableView: in your SDFormField subclass. You can register your custom cells there. I will add information in readme that this method needs to be overriden when subclassing.

**Comment by abuazizeh** [comment]
You can actually only override the defaultBundle method
- (NSBundle *)defaultBundle {
  NSBundle *mBundle=[NSBundle mainBundle];
  
  return mBundle;
  }

**Comment by rkwiat89** [comment]
Yes, that's another solution.
